name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Deno
        uses: denoland/setup-deno@v1
        with:
          deno-version: v2.x

      - name: Verify formatting
        run: deno fmt --check

      - name: Run linter
        run: deno lint

      - name: Type check
        run: deno check main.ts lib/hash.ts

      - name: Run tests
        run: deno test --allow-read --allow-write

      - name: Test CLI functionality
        run: |
          deno run --allow-read main.ts --help
          deno run --allow-read main.ts -a sha-256 main.ts

      - name: Test JSR publish (dry run)
        run: deno publish --dry-run
